### ISSUE TITLE
TypeError: unorderable types (Python 3)

### ISSUE THREAD

**Issue by selurvedu** [nxsofsys/jsondiff#2]
`jsondiff.py` doesn't compare lists properly on Python 3. Here's an example (on Python 3.4.3):

``` python
>>> import jsondiff
>>> jsondiff.make(['foo', 'bar'], [1234, 'foo'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/selurvedu/jsondiff/jsondiff.py", line 281, in make
    _compare_values('', None, info, src, dst)
  File "/home/selurvedu/jsondiff/jsondiff.py", line 275, in _compare_values
    _compare_lists(_path_join(path, key), info, src, dst)
  File "/home/selurvedu/jsondiff/jsondiff.py", line 261, in _compare_lists
    _item_added(path, key, info, new)
  File "/home/selurvedu/jsondiff/jsondiff.py", line 205, in _item_added
    index = _take_index(info.removed, item)
  File "/home/selurvedu/jsondiff/jsondiff.py", line 45, in _take_index
    if a[mid][0] < x: lo = mid+1
TypeError: unorderable types: str() < int()
```

I've tried to figure out why it works on 2.x (I was like, "What? Why would one want to compare different types implicitly? Why doesn't that even cause an exception!?") and stumbled upon [this](https://stackoverflow.com/questions/3270680/how-does-python-compare-string-and-int) question on SO. It explains a lot, but now I'm more confused by your code (`if a[mid][0] < x: lo = mid+1`). I don't understand what it was supposed to do. Can you explain?

P. S. Even though your tool has some problems, it is still better that diff generator in python-json-patch. Cheers!

**Comment by nxsofsys** [comment]
I need some time to review that problem =)
That code is some adaptation of bisect algorithm used here https://docs.python.org/2/library/bisect.html. I just putting all added/removed items in sorted array to find them later if they can be moved. In early versions I converted everything to frozenset, but it has some performance issues. Maybe, frozensets can be to fix problems in python3.

**Comment by selurvedu** [comment]
Huh... Can you provide some sort of comparison for performance info?

Also, does #1 affect performance anyhow?

**Comment by nxsofsys** [comment]
You can try it now, I think it's good enough for py3 =)

**Comment by selurvedu** [comment]
Thanks, it works on Python 3 now, but it doesn't work anymore on Python 2.6. See #3.
